os:
- linux
services:
- docker
language: node_js
node_js:
- 12.14.0
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.gradle"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=12.14.0
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - JHI_DISABLE_WEBPACK_LOGS=true
  - NG_CLI_ANALYTICS="false"
  - secure: n/5NHXOP1z8Ju5qQekoAhJREx/xKaT40osEv+TC7iQYi27qB7jXpLZJZGEz62fK6uOPicMa+MqfrSzhV01Qj/eHF1mKwfTrW5sRhAfNpqPBw3dMvFiYg2lHwfhSRPtwa08RCcPI941gc2ZqZ2Cr79Ucc0jF066nSxr5FLj6FJsNV9YvIn5nD4x9XgsvUB/mPvsJNTz685dDhKK2IR9fOVti9Ieyrc9c+AtLsT/NeXbwI02kDTK9FfajxKhBm2mydJfEeR9H/a82Dq/99U4HJfQNe3phFRst2C3ch9ZX5SO2bvHRRsosBH8GG8vuvl7x1YMfIUlXjUWgV+YdPOIHIKepohP1cl9dQJIt7QqlH6cYCYJ/lt9BOeQmnBiw4GhR7ZB5rI0IjmsaUO9JhEGYSB+eWTRz/67CNnVd200kRogREG8NIFmY+aoz5QBp3o0/DlVQtQWvxreJ7/dUAFlBcPrUT4j7ZO69UiWViKroQoWWDJYH5JQsiRASh+qvPrgpHBKdlRjDeNMcTq+AcvSy4fVjFbcNbrSCdJOUxIKU11dWorOOXPyBCrwlj499hK67D7E/pmX2n0OT65nNqPoqYPiKkeDHPn7OH4i8Cp8TmYGS2SD1NeO5lUt79ibkQzOtoMmuJfDKfS8tHu1kp0SMll8Av7quqcgqWWOpk+EGSy/w=
before_install:
- |
  if [[ $JHI_JDK = '8' ]]; then
    echo '*** Using OpenJDK 8'
  else
    echo '*** Using OpenJDK 11 by default'
    sudo add-apt-repository ppa:openjdk-r/ppa -y
    sudo apt-get update -q
    sudo apt-get install -y openjdk-11-jdk -y
    sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
    java -version
  fi
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- chmod +x gradlew
- "./gradlew checkstyleNohttp"
- "./gradlew clean test integrationTest"
- if [ $TRAVIS_PULL_REQUEST == "false" ]; then ./gradlew sonarqube --no-daemon -Dsonar.organization=handspy
  -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN; fi
- "./gradlew bootJar -Pprod -x test"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
